FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libprotobuf-dev \
    gcc \
    g++ \
    make \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-embed.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app
COPY embed/embed.py /app
COPY wait-for-preprocess.sh /app/wait-for-preprocess.sh
RUN chmod +x /app/wait-for-preprocess.sh
ENTRYPOINT ["/app/wait-for-preprocess.sh", "python", "embed.py"]
