FROM python:3.11-slim
RUN apt-get update && apt-get install -y \
    libprotobuf-dev \
    gcc \
    g++ \
    make \
    && rm -rf /var/lib/apt/lists/*
COPY requirements-cluster.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
WORKDIR /app
COPY cluster/cluster.py /app
COPY wait-for-embed.sh /app/wait-for-embed.sh
RUN chmod +x /app/wait-for-embed.sh
ENTRYPOINT ["/app/wait-for-embed.sh", "python", "cluster.py"]
