version: '3.8'

services:
  preprocess:
    build:
      context: .
      dockerfile: Dockerfile-preprocess
    volumes:
      - data:/app/data

  embed:
    build:
      context: .
      dockerfile: Dockerfile-embed
    volumes:
      - data:/app/data
    depends_on:
      - preprocess

  cluster:
    build:
      context: .
      dockerfile: Dockerfile-cluster
    volumes:
      - data:/app/data
    depends_on:
      - embed

volumes:
  data:
