#PREPROCESSING

import stanza
import pandas as pd
from tqdm import tqdm

stanza.download('es')
nlp = stanza.Pipeline('es', processors='tokenize,mwt,pos,lemma', batch_size=16)

data = [
    "Café orgánico de Colombia",
    "Suplemento vitamínico para niños",
    "Curso de programación en línea",
    "Entradas para concierto de rock",
    "Camisa de algodón azul",
    "Apartamento en la playa",
    "Guía de viaje a París",
    "Sopa instantánea de pollo",
    "Cámara fotográfica profesional",
    "Clases de baile flamenco",
    "Pantalones vaqueros negros",
    "Juego de sábanas de seda",
    "Bicicleta eléctrica plegable",
    "Kit de pintura al óleo",
    "Aceite de oliva virgen extra",
    "Consulta médica online",
    "Revista de historia antigua",
    "Botas de montaña impermeables",
    "Alojamiento rural con piscina",
    "Mapa interactivo de Nueva York",
    "Té verde japonés matcha",
    "Gafas de sol polarizadas",
    "Libro de poesía contemporánea",
    "Yoga mat antideslizante",
    "Kit de costura para principiantes",
    "Exposición de arte moderno",
    "Mermelada casera de frutos rojos",
    "Curso de inglés intensivo",
    "Vestido de fiesta elegante",
    "Apartamento amueblado en el centro",
    "Entradas para parque de atracciones",
    "Tablet con pantalla retina",
    "Set de herramientas de jardinería",
    "Concierto de música clásica",
    "Chaqueta deportiva transpirable",
    "Lámpara de pie vintage",
    "Kit de snorkel profesional",
    "Consulta nutricional personalizada",
    "Documental sobre el universo",
    "Zapatillas de running ultraligeras",
    "Puzzle de 1000 piezas",
    "Paella española lista para comer",
    "Curso de fotografía de naturaleza",
    "Traje de baño para mujer",
    "Casa adosada en urbanización",
    "Excursión guiada por Machu Picchu",
    "Infusor de té de acero inoxidable",
    "Set de acuarelas profesionales",
    "Aceite esencial de lavanda",
    "Consulta psicológica online",
    "Ballet clásico en el teatro",
    "Camiseta de fútbol del equipo local",
    "Maleta de viaje resistente",
    "Película de cine independiente",
    "Bufanda de lana tejida a mano",
    "Lámpara LED de escritorio",
    "Bicicleta estática con monitor LCD",
    "Manual de historia del arte",
    "Almohadas ergonómicas viscoelásticas",
    "Curso de cocina italiana",
    "Abono mensual para gimnasio",
    "Serie de cómics de ciencia ficción",
    "Vino tinto reserva Rioja",
    "Servicio de limpieza a domicilio",
    "Safari fotográfico en África",
    "Altavoces Bluetooth impermeables",
    "Taller de escultura en mármol",
    "Juego de cubiertos de plata",
    "Camisón de seda natural",
    "Tinte para cabello sin amoníaco",
    "Película documental sobre medio ambiente",
    "Altar budista de madera tallada",
    "Visita guiada a museo de arte moderno",
    "Chaqueta de cuero genuino",
    "Manta eléctrica de microfibra",
    "Curso de derecho constitucional",
    "Cama nido con colchones incluidos",
    "Safari fotográfico en selva amazónica",
    "Set de brochas profesionales de maquillaje",
    "Abono para concierto de música electrónica",
    "Pendientes de plata con piedras semipreciosas",
    "Bicicleta de montaña con suspensión completa",
    "Cuadro de pintura abstracta al óleo",
    "Guantes de esquí impermeables",
    "Manual de arquitectura contemporánea",
    "Joyero de madera con incrustaciones",
    "Taza de cerámica pintada a mano",
    "Servicio de diseño de interiores",
    "Kit de herramientas de reparación de bicicletas",
    "Serie de novelas históricas",
    "Kit de bordado para niños",
    "Servicio de consultoría financiera personalizada",
    "Raqueta de tenis de alta gama",
    "Recorrido en barco por el delta del Danubio",
    "Sartén antiadherente de titanio",
    "Sesión de masaje relajante",
    "Curso de marketing digital avanzado",
    "Guía gastronómica de Barcelona",
    "Álbum de fotografías familiares",
    "Set de toallas de algodón egipcio"
]

data_test = [
    "CAFE ORO SOBRE 45GRS X 48U",
    "V.ASADO CERDO..",
    "PASAJE AUTOBUS: GUAYAQUIL -> JIPIJAPA, 2024-06-01 09:30:00",
    "MIGRAX COM-RECX450/40MGX10",
    "HUEVO FRITO",
    "EGO CERA PARA PEINAR 160 ML",
    "CEBOLLA PUERRO.",
    "DETER LIMON CICL",
    "PRIME PET ALIM.COCIDO.",
    "MANZANA 355 ML",
    "TARRINA",
    "SPRITE",
    "AMOR WAFFER CHOCOLATE",
    "PULP MANGO",
    "PANOLINI DELICARE PANAL P E1",
    "LA VAQUITA NUTRIMAS..",
    "PROTEC NOSOTRAS DIARIOS MULTIX60",
    "INTERES POR CONSUMOS DIFERIDOS",
    "TRAT BAMBU NUT PANTE",
    "ALL NATURAL BOTELLON LIQUIDO 2",
    "PAPA RIZADAS 100GR LIMON X 24",
    "PH CLASICO MI C",
    "GASEOSA",
    "BEBIDA HIDRATANTE SPORADE 1.2",
    "TIPS SPRAY AMBIENTAL HAWAIIAN BEACH",
    "CICLON DETERG.POLVO SUAVIZANTE 600 G",
    "ELICOPTERO 117 PCS ARMAR",
    "OLE TOTOPOS TORTILLAS DE MAIZ NATURAL",
    "6 PRESAS BROASTER MAS PAPAS",
    "CEPILLO DENTAL INFANTIL COLGAT",
    "RECAMIER / SALON IN",
    "KIOSKO Q.MOZARELLA",
    "AGUA DASANI",
    "BULLDOG 12 KGS",
    "BANDEJITA SENCILLA",
    "BE FREE MANI CON CHOCOLATE 50G",
    "LO.MORTADELA ESPECIAL",
    "105 MINI ENROLLADO",
    "SURF POLVO EXPLOSION CITRICA",
    "AGUA DASANI S-GASX600MLX1 PET",
    "GASEOSAS MEDIANAS",
    "CONO SIMPLE",
    "COLGATE CEP.EXTRA CLEAN DURO PREC.ESPE.X2",
    "BROCOLI.",
    "VASO DESECHABLE 5.5 OZ HOME CL",
    "LIMONADA CON SODA",
    "CEREAL TRIGO&LECHE F",
    "DELIPAN MINI OREJAS CON CHOCOLATE",
    "HUEVO FRITO",
    "BURGER BITTERSWEET ROYAL",
    "LA LECHERA LECHE CONDENSADA DOY PACK",
    "CAFE ALAMOR 400GX50U ROJO //",
    "BEBIDA HIDRATANTE SPORADE TETR",
    "DETERG 1.2KG FLORAL",
    "EL ARTESANAL VINAGRE BLANCO",
    "INTERES POR CONSUMOS DIFERIDOS",
    "LO.LECHE EN POLVO ORD",
    "ORG TERRASANA ESPINACA BABY",
    "SUPER MARIO MONEDA CORREDORES OLA 1",
    "CB CK TENDER R",
    "BISTEC TACO",
    "LO.DULCE DE LECHE",
    "2 FILETES PULPA BRAZO (T)",
    "KINDER CHOCOLATE",
    "CEPILLO MADERA REF: 423793",
    "ALITAS BBQ TARIKO X 6",
    "DUOKN+6NUG UBER",
    "CARTON CORRUGADO PLIEGO SURTIDO",
    "SPAGHETTI ORIENT",
    "AGUA C/GAS SPLENDOR 1.5 L",
    "HABAS TIERNAS",
    "AZUCAR MORENA 1KG MI",
    "MAGGI MAYONESA DOYPACK",
    "INTERES POR CONSUMOS DIFERIDOS",
    "HARINA  MI CO",
    "LAVAPLATOS CREMA",
    "TONI MIX YOGURT FRUTILLA",
    "ELITE PH SOFT STRONG TH.GRD 4X20 M",
    "MIRAFLORES CREMA DE LECHE",
    "SPRITE SA",
    "HIELO ALL NATURAL 2.5 KG",
    "PAN MOLDE BLAN SUPAN",
    "PAN MOLDE SANDUCHERO MODERNA 8",
    "SX.DISCOS DESMAQUILLANTES X80",
    "TORTA CHOCOLATE CON MANJAR",
    "CORTE IMPRESO DE ESTADO DE CREDITO",
    "GOMAS MOGUL 150 G GUSANOS",
    "ACEITE FCO GIRAS",
    "GASEOSAS MEDIANAS",
    "SX.VASO BLANCO 5.5OZ",
    "ZAPATO NINA PAMPILI T 33 BICOLOR",
    "BANCHIS CHIFLES CEBOLLA",
    "SX.JAMON DE PAVO PARA SANDUCHE",
    "ENSURE ADVANCEVAINIL",
    "SALTIN NOEL TRITACO",
    "BONYURT GALLET BLACK",
    "UND. LLAVE FIRENZI 3410 P/LAVAMANOS ACRILICA",
    "COLGATE PACK TRIPLE ACC.PRECIO ESPEC 3X150ML",
    "POWERADE FRUTAS TROPICALES",
    "ESTROPAJO BRON ESTR",
    "DETERG FLORAL GOL",
    "COCA ZERO",
    "EXTRA CON ETANOL",
    "PORCION DE ARROZ",
    "PAPEL HIGIENICO DOBL",
    "LO.CARBON 3.5KG",
    "ANTIOQUENO AGUARDIENTE SIN AZUCAR",
    "MAQUINA P/AFEITAR BIC SENSITIV",
    "ISABEL ATUN LOMITOS ACEITE",
    "BASE LECHUGA",
    "BEB APPLE PET SPOR",
    "CLIGHT MULTIPACK SA",
    "MOLIDA TIPO I MENOS DEL 1% GRASA RES..",
    "CB CHICK&CHEE S",
    "LIMPOL LIMON",
    "CORTE IMPRESO DE ESTADO DE CREDITO",
    "VASO DE HELADO SWEET & COFFEE",
    "PEQUE COLOR 4T",
    "MIAS WAFER VAINILLA",
    "MI PRIMERA CAMERA",
    "CB PAPA MED",
    "[6062423]MAYONESA PICANTE CORTESIA",
    "GLP",
    "DEL VALLE NECT NARAN",
    "POLLO ESPECIAL",
    "PACK PARMALAT LECHE ENTERA FDA",
    "INTERES POR CONSUMOS DIFERIDOS",
    "NATURES HEART BEBIDA ALMENDRA SL",
    "AGUA SIN GAS",
    "TONI YOGURT MET150 FRESA",
    "SNOB ACEITUNA DESCAROZADA DOYPACK",
    "SNICKERS",
    "TE HELADO 12OZ",
    "00BBA3838-BA-12-23 CAMISETA M/C ROSADO T.18M",
    "POWERADE UVA",
    "SERV NORMAL MI COM",
    "PARCHE LEON HANSAPLAST GRANDE",
    "EXTRA",
    "FACUNDO LASAGNA",
    "LECHUGA CRESPA FUNDA",
    "INTERES POR CONSUMOS DIFERIDOS",
    "FUNDA PASTILLERA 4X6 PAQT X 1000",
    "FACUNDO MAIZ DULCE",
    "EXTRA",
    "SECO DE POLLO",
    "FUNDAS CAMISETA GRANDE BIODEGRADABLE",
    "105 BOLA DE AGUA",
    "LADY SS CREMA DESOD. CLINICAL COMPLETE POWDER",
    "FIDEO RAPIDITO ORIENTAL 65 G P",
    "INTERES POR MORA",
    "JUEGO DE TAZAS CERAMICA REF: 529-44-B",
    "RAPIDITO ORIENTAL CAR/FDA 100GR (24)",
    "TAXANID TAB-RECX500MGX6",
    "COCA COLA",
    "PERLA SUAVISANTE FRUT.ROJ",
    "COLGATE CD TRIPLE ACCION BLANCURA",
    "0.99 ARANDANO HF",
    "CHEESECAKE PISTACHO UIO PORCION",
    "DORINA MARGARINA ORIGINAL",
    "AZUCAR BLANCA MI CO",
    "LAPIZ ETERNO KAWAI",
    "RECARGO COBRANZAS POR PAGO TARDIO",
    "6PACK AMATI BEB AMARANTO MARAC/UVIL",
    "SNOB PINAS ALMIBAR S/AZUCAR",
    "A-PECHO S/HUESO RES...",
    "PINGUINO MAGNUM ALMENDRAS",
    "DIFUSOR ESENCIA VAIN",
    "FRUTILLA",
    "EXTRA CON ETANOL",
    "TOA HUM NAPPIS FISHER PRICE X20UNI",
    "PACK SAVITAL SH.AC. MULTIVITAMINAS",
    "CHAKANA PINTAA",
    "TE FUZE TEA 550 ML MANGO MANZA",
    "CREMA DE LECHE",
    "STIKERS VARIOS",
    "RECARGA AUTOMAT CLARO",
    "INTERES POR CONSUMOS DIFERIDOS",
    "LO.SUCEDANEO DE JUGO DE LIMON",
    "REYROCKER YOGURT SURTIDO",
    "CHURU TUNA WITH SALMON RE",
    "PACK STDO X6 TONI",
    "CEBOLLA COLORADA C/CASCARA MAL",
    "EXTRA",
    "NUTRIPLUS GEL 120 GRM",
    "0.99 PERA IMP BS",
    "COMBO DUO NACHO: RONDITOS EMPACADOS",
    "PIMIENTO VERDE GRANEL.",
    "BICICLETA 16&AMP;AMP;QUOT; DE NINA SWEET PEA",
    "AVENA GRANEL X LB",
    "PALMOLIVE JAB. GRANADA 3X110 G",
    "AMERICANO CON LECHE 12 OZ",
    "SG LOS ANDES SALSA TOMATE ECONOPACK.",
    "AGRO CHORIPAN DE RES TIPO ARGENTINO X6.",
    "PICADITAS DE EMBUTID",
    "VITA LECHE DESCREMADA 900 ML",
    "AGUA TESALIA DE 6 LITROS",
    "AMOR WAFER LIMON",
    "EMPANADAS DE CARNE QUITO",
    "AZUCAR MORENA",
    "BUPREX MIGRA COM-RECX400/100MGX20",
    "MONSTER ZERO ULTRA 473ML",
    "CATEGORIA 1",
    "ECO PAIS",
    "AK.PISTACHO",
    "INTERES POR CONSUMOS DIFERIDOS",
    "CUBRECAMA TILES COMFORTER",
    "PELUCHE PAS MIGHTY",
    "MASH",
    "MENESTRA",
    "B7 MM CV RIB E1 M TALLA XS COLOR ROSADO",
    "MARACUYA COCO",
    "KRASH POPCORN SABOR CARAMELO",
    "SUQUINI GRANEL.",
    "NITROESPECIAL TEMPORADA",
    "TOSTACHOS FIESTA 180GR",
    "AJO CONDIMENTO ILE",
    "CEPIMAX CEP.INTERDENTAL2 REPUESTOS",
    "SEMBRAO MINI PIMIENTOS DULCES MIX",
    "NO QUESO",
    "AK.AGUA C/GAS NATURAL",
    "MANZANA VERDE IMPORT",
    "FAMILIA SERVILLETA ACOLCHAMAX NORMAL 50 UND GRATIS",
    "VASO DE VIDRIO 18 OZ C/SACACOR",
    "PERA VERDE CON ROJA IMPORTADA.",
    "COCOA FDA LA UNIVER",
    "TUMIX VALUE CLOROFILA SANDIA",
    "LIMONADA DE CAFE",
    "INTERES POR CONSUMOS DIFERIDOS",
    "PASION MARACUYA PORCION",
    "PLUMA",
    "CANGUIL",
    "LIMON GRANDE GRANEL",
    "GUITIG",
    "HAMG COLONIAL",
    "CREPE 3 MIXTO",
    "PEREJIL",
    "*MERME GUSTA VASO 270 MORA-GUAYA-FRUTIMORA-DURAZN",
    "FLORES DECORATIVA ARTIFICIALES",
    "LEVADURA MACA POLVO 1KG. ECUANATU",
    "GELATINA EN POLVO GELLOW 500 G",
    "PATAS Y PESCUEZOS..",
    "CUAD COSIDO GENERICO",
    "O.B. TAMPON ORIGINAL SIEM.LIBRE MEDIO X16 U",
    "BATIDORAS DE MANO_OSTER 2499 013 000 5 VELOCIDADES_BLANCO",
    "SANDIA ESPECIAL PORCION",
    "COMINO ILE 50GR SOBRE GRAN 12UNI X12DISP",
    "FLORALP RICOTA UNTABLE.",
    "ZAPATO NINO DEPORTIV",
    "KANPU PAPA SUPER CHOLA DE MESA",
    "INTERES POR CONSUMOS DIFERIDOS",
    "YA HARINA S/POLVO PARA HORNEAR.",
    "RICAS GALLETA CAJA",
    "PAPAS FRITAS Y QUESO",
    "EXTRA CON ETANOL",
    "MODERNA SANDUCHERO INTEGRAL FAMILIAR",
    "CORTE IMPRESO DE ESTADO DE CREDITO",
    "DEJA DOY PACK LIQUIDO BABY",
    "SUPER PREMIUM 95",
    "PATO TANQUE PASTILLA",
    "BARQUILLO",
    "MOCACCINO 12OZ",
    "CREMA MANI SCHULL",
    "HELADO CONO SOFT",
    "MAXIPAN BAGUETTE BLANCO RUSTICO",
    "DULCE 3 LECHES",
    "MINI BUCKER",
    "SH.PROKPIL.POST.LAC.MILKERAT.300ML",
    "LA HOLANDESA Q.FRESCO BAJO/GRASA",
    "BBQ",
    "HORTANA LECHUGA ROMANA",
    "CHURRINES PERFECT MIX",
    "SUDADOS MARISCOS",
    "LECHE ENTERA FDA A",
    "JUGO TAMARINDOYA 15G",
    "SX.LIMPIA BANOS CON CLORO",
    "*FUNDA DE ACARREO",
    "MANITOBA MARANON SAL",
    "BEBIDA HIDRATANTE SPORADE 1.2",
    "MELON AMARILLO.",
    "FUNDA MEDIANA SIN MANIGUETA 6X10 PAQT X500",
    "DIABLO DARK RED",
    "ARVEJA FUNDA",
    "SG LOS ANDES MAYONESA ECONOPACK",
    "EXTRA",
    "JUGO PULP TETRABRIK 250 ML X 6",
    "ALIMENTO PURE NATURE AT-PESC GAX85G",
    "SHAMPOO",
    "DIESEL PREMIUM",
    "BUPREX FLASH 600 MG X 10 TABLETAS",
    "CHANCAPIEDRA 100 TABLETAS NATUALFA",
    "CHIPS AHOY",
    "ICED COFFEE 12 OZ",
    "GARBANZO",
    "ROSQUITAS TRENZADAS",
    "PLUM HAMBURGUESA ESTILO PARRILLERA",
    "MANZANA VERDE KG",
    "SH CARBON ACTV H&S",
    "INTERES POR CONSUMOS DIFERIDOS",
    "PACK KAARU YOG.GRIEGO NATURAL",
    "MANZANA VERDE GRANEL.",
    "BADIA SAZONADOR PARA POLLO"
]

categories = {
    "Vivienda": [
        "Lámpara", "mesa","Sofá", "Silla", "Escritorio", "Cortina", "Espejo", 
        "Cama elástica", "Colchón", "Refrigerador", "Estufa", "Horno", 
        "Lavadora", "Secadora", "Lavavajillas", "Microondas", "Tostadora", 
        "Licuadora", "Batidora", "Plancha", "Aspiradora", "Cepillo", 
        "Radiador", "Calentador", "Ventilador", 
        "Persianas", "Alfombra", "Mueble", "Estante", "Armario", "Cómoda", 
        "Cuna", "Hamaca", "Tocador", "Puff", "Candelabro", "Jarrón", 
        "Marcos de fotos", "Reloj", "Papel", "Luces", 
        "Almohada", "Sábana", "Edredón", "Mantas", 
        "Toallas", "Jabonera", "Cesto", "Organizador", 
        "Espejo", "Cortina", "Felpudo", "Escalera", 
        "Martillo", "Destornillador", "Taladro", "Sierra", 
        "herramientas", "Escalera", "Candado","Extintor", 
        "Alarma", "Timbre", "deter"
    ],
    "Educacion Arte y Cultura": [
        "Libro", "Revista", "Clase", "Curso", "Concierto", "Teatro", "Pintura",
        "Escultura", "Música", "Instrumento", "Partitura", "Biblioteca",
        "Exposición", "Arte", "Danza", "Ópera",
        "Fotografía", "Documental", "Película", "Cine", "Arquitectura",
        "Literatura", "Poema", "Novela", "Biografía",
        "Teatro", "Artesanía", "Graffiti",
        "Conferencia", "Seminario",
        "Taller", "Feria",
        "Libros", "Revistas", "Periódicos", "Publicaciones", "educativo",
    ],
    "Salud": [
        "Consulta", "Médico", "Salud", "Suplemento", "Vitamínico", "Nutrición",
        "Farmacia", "Hospital", "Clínica", "Ambulancia", "Vacuna", "Medicina",
        "Terapia", "Psicología", "Dentista", "Óptico", "Enfermería",
        "Quiropráctico", "Homeopatía", "Acupuntura", "Masaje", "Rehabilitación",
        "Seguro médico", "Prueba médica", "Laboratorio", "Ortopedia",
        "Primeros auxilios", "Bienestar", "Fitness", "Ejercicio", "Yoga",
        "Dieta", "Prevención", "Higiene", "Estimulante",
        "Analgesico", "Tratamiento", "Emergencia", "dental",
        "Optometría", "Atención primaria", "Centro de salud", "migrax", "colgate",
        "dental", ""
    ],
    "Alimentacion": [
        "café", "Té", "Sopa", "Frutas", "Verduras", "Carne",
        "Pescado", "Mariscos", "Huevos", "Leche", "Queso", "Yogur", "Pan",
        "Cereales", "Arroz", "Pasta", "Aceite de oliva", "Vinagre", "Sal",
        "Especias", "Hierbas", "Azúcar", "Miel", "Mermelada", "Chocolate",
        "Dulces", "Snacks", "Frutos secos", "Agua",
        "Refresco", "Zumos", "Batidos", "Vino", "Cerveza", "Licor", "Whisky",
        "Sidra", "Champán", "Aperitivos", "Helado", "Postres", "orgánico",
        "gourmet", "gluten", "veganos", "cereal", "yogurt", "gaseosa"
        "vegetarianos", "probióticos", "prebióticos", "cerdo", "manzana",
        "mora", "banano", "frutilla", "coco", "sandia", "pera", "piña", "pollo"
        "caldo", "maggi", "nestle" , "dasani" , "hidratante", "chocolate" ,
        "bistec", "gaseoso", "filete", "agua", "haba", 
    ],
    "Vestimenta": [
        "Camisa", "Pantalón", "Vestido", "Zapato", "Chaqueta", "Abrigo", "Bufanda",
        "Gorra", "Sombrero", "Gafas de sol", "Calcetines", "Ropa interior", "Pijama",
        "Traje", "Corbata", "Cinturón", "Bolso", "Cartera", "Collar", "Pulsera",
        "Anillo", "Reloj", "deportivas", "Sandalias", "Botas",
        "casual", "formal", "urbana", "retro",
        "elegante", "unisex", 
        "Lencería"
    ],
    "Turismo": [
        "Viaje", "Guía", "Excursión", "Turismo", "Safari", "Hotel", "Alojamiento",
        "Reserva", "Vuelo", "Crucero", "Playa", "Montaña", "Ciudad", "País",
        "Continente", "Tour", "Ruta", "Mapa", "GPS",
        "Parque", 
        "Museo", "Monumento", "histórica",
        "Evento", "local",
        "Ecoturismo", "Aventura", "Excursión",
        "Transporte", 
        "Pasaporte", "Equipaje", "Maleta", "Mochila", "Cámara",
        "Recuerdos", "Souvenirs","Compras"
    ],
    "Otro": [
        "Cigarillos", "Gasolina", "Electrodomésticos", "Electrónica", 
        "Juguetes",
        "belleza", "higiene",
        "Juegos", "desmaquillante",
        "Perfume", "Maquillaje"
    ]
}

processed_data = []
for sentence in tqdm(data, desc="Processing Descriptions"):
    sentence = sentence.lower().strip()
    doc = nlp(sentence)
    
    keywords = []
    lemmas = []
    for sent in doc.sentences:
        for word in sent.words:
            if word.upos in ["PROPN", "NOUN", "ADJ"]:
                keywords.append(word.text)
                lemmas.append(word.lemma)
                
    joined_lemmas = " ".join(lemmas)
    processed_data.append({"Sentence": sentence, "Keywords": keywords, "Lemmas": joined_lemmas})

processed_data_test = []
for sentence in tqdm(data_test, desc="Processing Descriptions"):
    sentence = sentence.lower().strip()
    doc = nlp(sentence)
    
    keywords = []
    lemmas = []
    for sent in doc.sentences:
        for word in sent.words:
            if word.upos in ["PROPN", "NOUN", "ADJ"]:
                keywords.append(word.text)
                lemmas.append(word.lemma)
                
    joined_lemmas = " ".join(lemmas)
    processed_data_test.append({"Sentence": sentence, "Keywords": keywords, "Lemmas": joined_lemmas})

processed_cat = []
for sentence in tqdm(categories.keys(), desc="Processing Descriptions"):
    list_aux = categories[sentence]
    for i in list_aux:
        j = i.lower().strip()
        doc = nlp(j)
        keywords = []
        lemmas = []
        for sent in doc.sentences:
            for word in sent.words:
                if word.upos in ["PROPN", "NOUN", "ADJ"]:
                    keywords.append(word.text)
                    lemmas.append(word.lemma)
                
        joined_lemmas = " ".join(lemmas)
        processed_cat.append({"Sentence": sentence, "Keywords": keywords, "Lemmas": joined_lemmas})

df = pd.DataFrame(processed_data)
df_test = pd.DataFrame(processed_data_test)
df_cat = pd.DataFrame(processed_cat)


df['Lemmas']=df['Lemmas'].str.normalize('NFKD').str.encode('ascii',errors='ignore').str.decode('utf-8')
df_test['Lemmas']=df_test['Lemmas'].fillna('').str.normalize('NFKD').str.encode('ascii',errors='ignore').str.decode('utf-8')
df_cat['Lemmas']=df_cat['Lemmas'].fillna('').str.normalize('NFKD').str.encode('ascii',errors='ignore').str.decode('utf-8')

print(df_cat)
print(df)

df.to_csv("/app/data/processed_data.csv", index=False)
df_test.to_csv("/app/data/processed_data_test.csv", index=False)
df_cat.to_csv("/app/data/processed_data_cat.csv", index=False)